import plus from "../../assets/plus.svg";

const dummyData = [
  {
    files: plus,
    title: "나이키 신발",
    price: 240000,
    description: "나이키 운동화 사이즈 300",
    productId: 1,
  },
  {
    files: plus,
    title: "아디다스 신발",
    price: 340000,
    description: "아디다스 삼선 슬리퍼 사이즈260",
    productId: 2,
  },
  {
    files: plus,
    title: "닥터마틴 로퍼",
    price: 270000,
    description: "닥터마틴 로퍼 사이즈 270",
    productId: 3,
  },
  {
    files: plus,
    title: "흰색 셔츠",
    price: 20000,
    description: "미개봉 흰색 셔츠",
    productId: 4,
  },
  {
    files: plus,
    title: "나이키 신발",
    price: 240000,
    description: "나이키 운동화 사이즈 300",
    productId: 5,
  },
  {
    files: plus,
    title: "아디다스 신발",
    price: 340000,
    description: "아디다스 삼선 슬리퍼 사이즈260",
    productId: 6,
  },
  {
    files: plus,
    title: "닥터마틴 로퍼",
    price: 270000,
    description: "닥터마틴 로퍼 사이즈 270",
    productId: 7,
  },
  {
    files: plus,
    title: "흰색 셔츠",
    price: 20000,
    description: "미개봉 흰색 셔츠",
    productId: 8,
  },
  {
    files: plus,
    title: "나이키 신발",
    price: 240000,
    description: "나이키 운동화 사이즈 300",
    productId: 9,
  },
  {
    files: plus,
    title: "아디다스 신발",
    price: 340000,
    description: "아디다스 삼선 슬리퍼 사이즈260",
    productId: 10,
  },
  {
    files: plus,
    title: "닥터마틴 로퍼",
    price: 270000,
    description: "닥터마틴 로퍼 사이즈 270",
    productId: 11,
  },
  {
    files: plus,
    title: "흰색 셔츠",
    price: 20000,
    description: "미개봉 흰색 셔츠",
    productId: 12,
  },
  {
    files: plus,
    title: "나이키 신발",
    price: 240000,
    description: "나이키 운동화 사이즈 300",
    productId: 13,
  },
  {
    files: plus,
    title: "아디다스 신발",
    price: 340000,
    description: "아디다스 삼선 슬리퍼 사이즈260",
    productId: 14,
  },
  {
    files: plus,
    title: "닥터마틴 로퍼",
    price: 270000,
    description: "닥터마틴 로퍼 사이즈 270",
    productId: 15,
  },
  {
    files: plus,
    title: "흰색 셔츠",
    price: 20000,
    description: "미개봉 흰색 셔츠",
    productId: 16,
  },
  {
    files: plus,
    title: "나이키 신발",
    price: 240000,
    description: "나이키 운동화 사이즈 300",
    productId: 17,
  },
  {
    files: plus,
    title: "아디다스 신발",
    price: 340000,
    description: "아디다스 삼선 슬리퍼 사이즈260",
    productId: 18,
  },
  {
    files: plus,
    title: "닥터마틴 로퍼",
    price: 270000,
    description: "닥터마틴 로퍼 사이즈 270",
    productId: 19,
  },
  {
    files: plus,
    title: "흰색 셔츠",
    price: 20000,
    description: "미개봉 흰색 셔츠",
    productId: 20,
  },
  {
    files: plus,
    title: "나이키 신발",
    price: 240000,
    description: "나이키 운동화 사이즈 300",
    productId: 21,
  },
  {
    files: plus,
    title: "아디다스 신발",
    price: 340000,
    description: "아디다스 삼선 슬리퍼 사이즈260",
    productId: 22,
  },
  {
    files: plus,
    title: "닥터마틴 로퍼",
    price: 270000,
    description: "닥터마틴 로퍼 사이즈 270",
    productId: 23,
  },
  {
    files: plus,
    title: "흰색 셔츠",
    price: 20000,
    description: "미개봉 흰색 셔츠",
    productId: 24,
  },
  {
    files: plus,
    title: "나이키 신발",
    price: 240000,
    description: "나이키 운동화 사이즈 300",
    productId: 25,
  },
  {
    files: plus,
    title: "아디다스 신발",
    price: 340000,
    description: "아디다스 삼선 슬리퍼 사이즈260",
    productId: 26,
  },
  {
    files: plus,
    title: "닥터마틴 로퍼",
    price: 270000,
    description: "닥터마틴 로퍼 사이즈 270",
    productId: 27,
  },
  {
    files: plus,
    title: "흰색 셔츠",
    price: 20000,
    description: "미개봉 흰색 셔츠",
    productId: 28,
  },
  {
    files: plus,
    title: "나이키 신발",
    price: 240000,
    description: "나이키 운동화 사이즈 300",
    productId: 29,
  },
  {
    files: plus,
    title: "아디다스 신발",
    price: 340000,
    description: "아디다스 삼선 슬리퍼 사이즈260",
    productId: 30,
  },
  {
    files: plus,
    title: "닥터마틴 로퍼",
    price: 270000,
    description: "닥터마틴 로퍼 사이즈 270",
    productId: 31,
  },
  {
    files: plus,
    title: "마지막 셔츠",
    price: 20000,
    description: "미개봉 흰색 셔츠",
    productId: 32,
  },
];

export default dummyData;
